Разметка главной страницы мобильной
htmlacademy-adaptive/1425295-pognali-21 pull request #3
Opened 2020-11-27 09:09 UTC by MarinaIvantsova

2020-11-27 14:28 UTC, Katysheva requested changes

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +          <li class="socials__list-item">Facebook</li>
это всё ссылки

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +        <a class="contacts__mail" href="#">mail@htmlacademy.ru</a>
`href="mailto:mail@htmlacademy.ru"`

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +          <p class="promo__slogan">В путешествие<br>с крутыми<br>попутчиками!</p>
лучше на этом этапе не ставить разрывы строк

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +            Выберете направление
выберите

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +        <p class="about__description">Любое путешествие веселее<br>с попутчиками, которые на<br>одной волне с тобой!
на десктопе же текст иначе переносится, и как тогда?

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +            <div class="countries-list__description">
логичнее, если карточка страны будет БЭМ-блоком, а не список карточек

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +              <img class="countries__image-thailand-flag" src="https://via.placeholder.com/35x24">
имя класса привязано к контенту, а здесь, например, не Тайланд, а Франция. Должно быть не привязано - вид страны, флаг страны. Для конкретного флага можно добавлять модификатор

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +        <button class="Show" type="button">Показать все</button>
все свои классы лучше называть полностью строчными буквами, без заглавных

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +        <button class="Show" type="button">Показать все</button>
лучше тогда ссылка, чем тип `button`

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +            <!--Почему div-->
?

2020-11-27 14:28 UTC, Katysheva commented on source/index.html
> +            <button class="feedback__button button-registration" type="submit" aria-label="Регистрация"></button>
не надо кнопку внутрь лейбла класть

2020-11-28 05:05 UTC, MarinaIvantsova commented on source/index.html
> +            <div class="countries-list__description">
Не могу разобраться

2020-11-28 05:08 UTC, MarinaIvantsova commented on source/index.html
> +            <button class="feedback__button button-registration" type="submit" aria-label="Регистрация"></button>
почему?

2020-12-01 12:58 UTC, Katysheva approved these changes

2020-12-01 12:58 UTC, merged